[project]
name = "ecuria"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "docx>=0.2.4",
    "openpyxl>=3.1.5",
    "python-docx>=1.1.2",
    "pywin32>=308",
]

[dependency-groups]
dev = [
    "pre-commit>=4.1.0",
]
